name: Symfony CI

on:
  push:
    branches: [Master]
  pull_request:
    branches: [Master]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: symfony
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        extensions: mbstring, xml, ctype, iconv, intl, pdo_mysql
        coverage: none

    - name: Create .env.local file with default values
      run: echo "APP_ENV=dev\nDATABASE_URL=mysql://root:root@127.0.0.1:3306/symfony" > .env.local

    - name: Set up .env.local
      run: cp .env .env.local

    - name: Install Composer dependencies
      run: composer install --no-progress --no-suggest --prefer-dist

    - name: Run database migrations
      run: php bin/console doctrine:migrations:migrate --no-interaction

    - name: Run tests
      run: php bin/phpunit

    - name: Check Symfony versioning
      run: symfony self:update --dry-run
